### ISSUE TITLE
SVG minifier corrupts zeroes after floating numbers

### ISSUE THREAD

**Issue by RReverser** [tdewolff/minify#114]
### Before
```svg
<path d="M55.791 58.766c-.111-4.771-5.433-10.05-10.192-10.05H27.876c-4.759 0-10.081 5.28-10.192 10.05h-.009v24.397a3.28 3.28 0 0 0 3.279 3.28 3.274 3.274 0 0 0 3.276-3.279l.003-21.616h2.536V124.035c0 2.212 1.958 4.007 4.371 4.007 2.414 0 4.372-1.795 4.372-4.007v-36.71h2.449v36.711c0 2.212 1.959 4.007 4.372 4.007s4.371-1.795 4.371-4.007V61.549h2.536l.003 21.616a3.274 3.274 0 0 0 3.276 3.279 3.28 3.28 0 0 0 3.279-3.28V58.767l-.007-.001z"/>
```

![page-shot-2016-12-15 create a new pen](https://cloud.githubusercontent.com/assets/557590/21240174/fdcb45d0-c301-11e6-816d-b8c68657d22f.png)

### After
```svg
<path d="M55.791 58.766c-.111-4.771-5.433-10.05-10.192-10.05H27.876c-4.759.0-10.081 5.28-10.192 10.05h-.009v24.397a3.28 3.28.0.0.0 3.279 3.28 3.274 3.274.0.0.0 3.276-3.279l.003-21.616h2.536V124.035c0 2.212 1.958 4.007 4.371 4.007 2.414.0 4.372-1.795 4.372-4.007v-36.71h2.449v36.711c0 2.212 1.959 4.007 4.372 4.007s4.371-1.795 4.371-4.007V61.549h2.536l.003 21.616a3.274 3.274.0.0.0 3.276 3.279 3.28 3.28.0.0.0 3.279-3.28V58.767l-.007-.001z"/>
```

![page-shot-2016-12-15 create a new pen 1](https://cloud.githubusercontent.com/assets/557590/21240207/30a6907c-c302-11e6-8940-acacfc9776a0.png)

Unfortunately, I'm not too good at SVG to provide smaller meaningful example, but you can notice that in multiple occurences `[space]0` after a decimal number was turned into `.0` as if it's part of a previous decimal number:

* `c-4.759 0-` -> `c-4.759.0-`
* `a3.28 3.28 0 0 0 3.279 3.28 3.274 3.274 0 0 0` -> `a3.28 3.28.0.0.0 3.279 3.28 3.274 3.274.0.0.0`
* ...

**Comment by RReverser** [comment]
It appears that the problem is in `copyNumber` in `pathdata.go`, need to dig deeper to understand what that first statement was supposed to do / when such transformation is safe at all.

**Comment by tdewolff** [comment]
It is valid for pathdata to have multiple dots in the numbers. As soon as the parser finds a second dot, it assumes that it is a new number. The reason that the minifers adds dots aggresively, is that any subsequent numbers can remove the leading separating space.

The problem doesn't seem to be in the missing space before the dot though. Looking at `a3.28 3.28.0.0.0 3.279 3.28` which is an arc command, the problem is that the 4th and 5th parameter are the large-arc-flag and sweep-flag respectively. They can only be zero or one (false or true). Apparently `.0` is not considered to be `false`. I will fix this soon, thanks for the test case.

**Comment by RReverser** [comment]
I see - as I said, I'm not very good at SVG and not familiar with pathdata grammar, so thanks for explanations and the fix! I'll test it on some more problematic files and will report back.
