### ISSUE TITLE
minify deletes :root-declaration in css

### ISSUE THREAD

**Issue by vedam** [tdewolff/minify#126]
Hi,
I stumbled upon this while minifiying css.

in CSS-files I declare custom-properties in a :root-selector:
```
:root {
  --side-padding: 2rem;
}
```

style-declarations are using these custom-properties:
```
.side-padding {
  padding-left: var(--side-padding);
  padding-right: var(--side-padding);
}
```

with minify the :root-declaration is deleted, so custom-properties in style-declaration couldn't work.

**Comment by tdewolff** [comment]
This is invalid CSS because a declaration starts with an identifier and an identifier can not start with two dashes, see https://www.w3.org/TR/css-syntax-3/#ident-token-diagram. If you input your CSS into https://jigsaw.w3.org/css-validator/validator it will error. The parser chokes on the input, but perhaps a better way to treat this is to just output the bad CSS instead of removing it.

**Comment by vedam** [comment]
thx for the info.
I thought it is common practice using custom css-properties. I'm wrong.
Sorry for the noise.

**Comment by tdewolff** [comment]
I will reopen this issue, because I want to look into ignore invalid CSS instead of removing it.

**Comment by tdewolff** [comment]
This should be fixed in 6206d455c1d422a3aea430e73d7375e7a0d9cbf0

**Comment by tdewolff** [comment]
Apparently, `--*` style declarations are a proposal for the spec, see https://www.w3.org/TR/css-variables-1/

I will go and implement it anyways soon.

**Comment by vedam** [comment]
Very much appreciated. Thx a lot.
