### ISSUE TITLE
 Minify removes usable code

### ISSUE THREAD

**Issue by stp-ip** [tdewolff/minify#135]
Just noticed, that using minify on this code:
```html
<input type="text" name="name" id="name" placeholder="Name" />
```
is rewritten to:
```html
<input name="name" id="name" placeholder="Name" />
```

This actually breaks sites. Doesn't think this should be intentional. Wanted to log it here for now.

Thanks

**Comment by tdewolff** [comment]
The default value for `input[type]` is `text`, see https://www.w3.org/TR/html5/forms.html#attr-input-type and https://developer.mozilla.org/en/docs/Web/HTML/Element/input#Form_<input>_types at the bottom.

If a browser does not follow the spec, this is a bug in the browser. Can you specify what browser + version is causing this?

**Comment by stp-ip** [comment]
The input type is correctly used, but removing it might also remove styling associated with type=text.

browsers: firefox 52.0.2 and chromium 57.0.2987.133

**Comment by tdewolff** [comment]
If you want CSS to address all text areas, you should actually match not-specified, empty, `text` and any combination that is not a valid type value. See http://stackoverflow.com/questions/4113965/css-selector-for-text-input-fields This is the only way to adhere to the spec.

**Comment by tdewolff** [comment]
I agree this is not a very workable solution for most people. Perhaps a new option should be introduced for this since it has been requested before. I'm hesitant because really the CSS does not follow the HTML spec on this. But on the other hand you ensure that your HTML explicitly contains `type` attributes, you can assume this in your CSS I guess. The best way if you can alter CSS is to match both `input[type="text"]` and `input:not([type])`.

**Comment by stp-ip** [comment]
Thanks. Not a frontend person so thanks for laying out the spec etc. Much appreciated. Will switch the used themes to be valid.
