### ISSUE TITLE
undefined: minify.Bytes

### ISSUE THREAD

**Issue by dhoblem** [tdewolff/minify#152]
I am trying to get this module for one of my project as one of the dependency using "go get" command.
I am facing issue while building my project using the source of minify with below error: 
$ go get github.com/tdewolff/minify
cd /root/meghali/couchbase/ns_server/deps/gocode/src/minify
/root/meghali/go/pkg/tool/linux_ppc64le/compile -o $WORK/minify.a -trimpath $WORK -p main -complete -buildid 68084043dd0f5163b57f1f669cd711eb912a1bce -D _/root/meghali/couchbase/ns_server/deps/gocode/src/minify -I $WORK -I /root/meghali/couchbase/build/gopkg/go-1.8.1 -pack ./minify.go
# minify
../../../deps/gocode/src/minify/minify.go:153: undefined: minify.Bytes

The go version I am using is :1.8.1 
Has anyone seen this issue before? Any pointers would be helpful.

Thanks,
Meghali

**Comment by tdewolff** [comment]
Do you have the latest version of `minify`? You can use `go get -u github.com/tdewolff/minify`

Or is Couchbase using an old version of minify? `Bytes` used to be a global function, but it is now a member function of `*M`.

**Comment by dhoblem** [comment]
Hi @tdewolff , Thanks for your reply!
Yes, I have tried doing "go get -u github.com/tdewolff/minify" however that didn't help much. 
Couchbase is using go 1.8.1, not sure about the minify version. How do we see the minify version? 
I will try to find what version is couchbase expecting to have. 

Thanks,
Meghali

**Comment by mikegleasonjr** [comment]
Regarding multiple issues I myself faced with minify dependencies (for example, lack of semver with godep), I would suggest to merge `github.com/tdewolff/parse`, `github.com/tdewolff/buffer`, `github.com/tdewolff/strconv` into `Minify`. This would also be more Go idiomatic.

**Comment by tdewolff** [comment]
You mean to have subpackages in `minify` for `parse`, `strconv`, etc.? That is a good idea, but back when I set them up I wanted them to be completely separate and uncoupled. That would still be the case though when they are organized as subpackages, so I guess that could work.

What I don't get is why this is a problem with dependency managers though, is it that godep doesn't use semver, is that what you are saying?

**Comment by mikegleasonjr** [comment]
godep uses semver. I had problems with minify when de dependencies were out of sync due to lack of semver or the semver not being updated in a dependency.

Resorted to put exceptions to always fetch master but seeing this problem come up often, I would suggest to put the deps in the library itself (had that problem 2 times, seen it here in the issues 1-2 times).

**Comment by dhoblem** [comment]
Thanks @mikegleasonjr  and @tdewolff , for helping out with your responses. 
I could fix the issue as of now in my environment by refreshing the source for "minify" and the couchbase both. By refreshing the whole source; it fetched the compatible version for minify it seems and hence the issue got resolved. 
Thanks,
Meghali

**Comment by mikegleasonjr** [comment]
@tdewolff not with `godep`. It fetches the latest `semver` versions. So if you update let's say `buffer` and `minify` but you forget to tag `buffer`, things will break.

**Comment by tdewolff** [comment]
Ah I see, so the problem is that some packages (`buffer` for example) has changes in master that aren't tagged yet as a release?

**Comment by mikegleasonjr** [comment]
@tdewolff (while `Minify` has been released and tagged) yes exactly!

**Comment by tdewolff** [comment]
Alright, I've released new versions for minify and its dependencies.

**Comment by tdewolff** [comment]
@mikegleasonjr I want to revisit this proposal of merging the packages, because I too feel that there are too many dependencies on my own packages. Given that for the future I have more plans to use `parse` for other package (think about `fmt` or `lint`), I feel that the separation of `minify` and `parse` is justified. I do agree that the coupling is pretty strong, not just on the API but also on the behavior. Usually a behavioral change of `parse` requires changes in `minify` as well, not sure how to solve this with semver other than releasing a new major/minor version.

However, I feel that the `buffer` and `strconv` packages could be merged into `parse` (as subpackages, alongside `html`, etc.). This means `minify` depends on `parse`, but that `parse` depends on nothing else. Both depend on `test` for testing though, that will remain.

This would be a relatively easy change, as there are not many users of the `buffer` and `strconv` packages. What do you think?

**Comment by mikegleasonjr** [comment]
@tdewolff As a consumer of `Minify`, the least dependencies the better!

Congrats on your awesome release!

**Comment by tdewolff** [comment]
@mikegleasonjr Thanks! Much appreciated ;-)

I've merged `buffer` and `strconv` into `parse` on branch `master`. Let me know if that works for you, you need a new version for this?

**Comment by mikegleasonjr** [comment]
@tdewolff Any package that `Minify` depends on must have a `semver` if we want to use it with `dep`!
