### ISSUE TITLE
HTML: possible minifications

### ISSUE THREAD

**Issue by tdewolff** [tdewolff/minify#159]
* <del>Rewrite href="javascript:void(0)" to href="#"</del>
* Minify JS in href="javascript:..."
* If possible, minify other valid URLs such as mailto: (not sure if worthwhile)

**Comment by mikegleasonjr** [comment]
Pay attention to `href="javascript:void(0)"` to `href="#"`, it would change the meaning of a click:

1. when `javascript:void(0)`, it is preventing anything to happen, so a click would do nothing
2. when `#`, a click would make the page scroll to the beginning (since the anchor is not found on the page)

**Comment by tdewolff** [comment]
Good point, the other two points don't seem to occur that often. Maybe something for the future.
