### ISSUE TITLE
Equinox Build 2.2.0 Update

### ISSUE THREAD

**Issue by meepzh** [tdewolff/minify#160]
Hello!

I'm helping maintain the [Arch Linux user repo](https://aur.archlinux.org/packages/minify/) for your software, and we use your build on Equinox to stay up to date. Would you mind updating your page there with the 2.2.0 release?

If you want to drop support for Equinox, we can switch to your git repo, no problem.

Thanks!

**Comment by tdewolff** [comment]
Absolutely, I was planning to release new GitHub versions soon (there still a small thing I want to do in `buffer`, the back-end package) and then release for Equinox. I'll let you know here, should be really soon.

Thanks for maintaining the Arch package!

**Comment by tdewolff** [comment]
I'm thinking about switching to https://github.com/goreleaser/goreleaser instead of Equinox, because it integrates well with GitHub (keeping releases in one place) and is easier to use. Also, I had some problems with versioning with Equinox, as sometimes I made a mistake in a release. The nice thing about Equinox though was the ability to update applications through the application itself, but I believe it is better to let the package manager handle this (on Linux at least).

I think it might be easier if you were to depend on the git repository. Additionally, I want to add bash completion to the tool, how does that work with AUR releases? See https://github.com/spf13/cobra/blob/master/bash_completions.md, apparently a `minify.sh` file will need to be added to `/etc/bash_completion.d/`, although I do not have this directory (I run Arch as well).

**Comment by tdewolff** [comment]
By the way, I've released a new version: https://github.com/tdewolff/minify/releases/tag/v2.3.1

**Comment by meepzh** [comment]
Awesome! Under the file list for [bash completions](https://www.archlinux.org/packages/extra/any/bash-completion/), it seems like they're under `/usr/share/bash-completion/completions`.

We can modify the PKGBUILD script's package() function to install the completion file at that directory, like mentioned here: http://jlk.fjfi.cvut.cz/arch/manpages/man/PKGBUILD.5#PACKAGING_FUNCTIONS
As long as the script is in the archive, it should be really straightforward.

Thanks for the quick response and for the update! I'll get to updating the package on AUR soon. Feel free to close this if you'd like.

**Comment by tdewolff** [comment]
Nice! I filed bash completion under another issue. Let me know if you need anything for the Arch release
