### ISSUE TITLE
add a keep_comments option

### ISSUE THREAD

**Issue by bmintz** [tdewolff/minify#167]
I frequently use comments as messages to the brave visitor who dares to read the source code.

Please allow me to keep this notices.

**Comment by tdewolff** [comment]
I'm hesitant to 'bloat' the library with features like this. Either you want to minify your HTML or you don't. People insist on something in between, but the only reason I added the other options for HTML parsing is because other tools are not able to process HTML according to the specs. I would actually like to remove most of the options on the HTML parser in the future, because less is more.

Maybe you could use conditional comments for this...

**Comment by sergsmitienko** [comment]
I kindly ask you to reconsider your opinion. Comments are useful if you pass your html for external processing, like 'server side includes'
