### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by simlevesque** [tdewolff/minify#191]
I have a website that I make using a static site generator that I created. There are currently 14000 pages on the site and there will be many more. I tried to use other html minifier but they were all way too slow. I tried to use yours, using the pre-built 2.3.4 binary for Linux x86 64bit.
`955c4ed1e25db9257d97e08d91c02cd8  minify_2.3.4_linux_amd64.tar.gz`
`1d6622946b0ede530a6e4b29de1ce472  minify`

When I run this command:
`./minify --all -r --mime text/html  /home/sim/www/`

I get the following error:

```
ERROR: open /home/sim/www/articles/9879/index.html: too many open files
panic: interface conversion: interface is nil, not io.ReadCloser

goroutine 1 [running]:
main.minify(0x7ffeecc0f351, 0x9, 0xc4209b6000, 0x38a7, 0x3c00, 0x0, 0x0, 0x0, 0x0, 0xc42011a568)
	/home/taco/go/src/github.com/tdewolff/minify/cmd/minify/main.go:565 +0x916
main.main()
	/home/taco/go/src/github.com/tdewolff/minify/cmd/minify/main.go:197 +0x1324
```

**Comment by tdewolff** [comment]
This took me a while to figure out. I think you were somehow concatenating the files, in which case all files were loaded. This happens when you have a directory or multiple files as input, and only a single output file. In your case it was `os.Stdout` causing the concatenating. I've committed a fix, please test it and let me know of any bugs.
