### ISSUE TITLE
style attributes quotes are removed

### ISSUE THREAD

**Issue by yavuzyurtbegendi** [tdewolff/minify#192]
`<div style="background-color: #333;">`

becomes

`<div style=background-color: #333>`

it becomes a bit of a problem, how can i solve this issue ? it is the same in this website also

http://go.tacodewolff.nl/minify

**Comment by yavuzyurtbegendi** [comment]
I am sorry to be late to answer, I just got notified after you closed the issue, did not see your comment,
It is just an example, space removal works right, i just wanted to show quotation removal of style tag, it might be a problem on some browsers, quotations should remain i think

**Comment by tdewolff** [comment]
I don't believe so. The example you gave is not something that happens. Either it has the space and the quotes are kept, or the space is removed and the quotes as well. I don't think the problem you described is real...

**Comment by yavuzyurtbegendi** [comment]
https://ibb.co/gFFae7
This is the screenshot

**Comment by yavuzyurtbegendi** [comment]
this is another one
![screencapture-go-tacodewolff-nl-minify-2018-04-14-15_49_47](https://user-images.githubusercontent.com/8124908/38768382-9e5fd868-3ffb-11e8-88e6-99db97f7b938.png)

**Comment by tdewolff** [comment]
What you have shown is intended behaviour, it works correctly. What is the problem you are having with this? This should work in all (modern) browsers.

**Comment by yavuzyurtbegendi** [comment]
I am supporting old browsers also, I am writing a plugin, it might cause really nasty behavior to remove quotes.

**Comment by tdewolff** [comment]
Removing quotes is allowed since HTML4, which is very old. What browser are you experiencing this issue with? Sounds to me that browser is probably really really old, but in any case I don't really want to support old browsers. The whole minifier assumes HTML5 input and generates valid HTML5 output, if you have a browser doesn't follow the spec or doesn't implement HTML5, you should disable the minifier.
