### ISSUE TITLE
Change minify settings

### ISSUE THREAD

**Issue by EtienneBruines** [tdewolff/minify#21]
It would be nice to tell the minifier, which features we want, and which we don't. 

For example, the feature <i>'strip default attribute values and attribute boolean values'</i> (HTML Minifier) breaks compatibility with the `input[type=text]` fields when using [Foundation](https://github.com/zurb/foundation). It would be nice to be able to say: `StripDefaultValues = false` or something similar.

**Comment by tdewolff** [comment]
I would see how this would be practical, but I have several points against this.

* Feature toggles make minifying slower
* Breaks the no-configuration interface (makes the Minify interface a lot more complex)
* The minifiers follow the official specification, if someone else doesn't, it's not our problem

Foundation should really check for inputs with empty type attributes, because those are valid text inputs too. I think you should file a bug report there. Overhead (code and speed) is just too big, I'm sorry.

**Comment by omeid** [comment]
But this breaks MaterializeCSS, Foundation, and possibly bootstrap.

_Slow is less than ideal, broken is no deal._

**Comment by tdewolff** [comment]
Please check the `options` branch. It has an implementation for passing options to the minifiers. Be aware that the API might still change in that branch.

Let me know what you think!
