### ISSUE TITLE
cannot find package "github.com/tdewolff/minify/v2" 

### ISSUE THREAD

**Issue by eastdx** [tdewolff/minify#239]
go get -u github.com/tdewolff/minify/v2

package github.com/tdewolff/minify/v2: cannot find package "github.com/tdewolff/minify/v2" in any of:
        /usr/lib/golang/src/github.com/tdewolff/minify/v2 (from $GOROOT)
        /root/go/src/github.com/tdewolff/minify/v2 (from $GOPATH)

**Comment by tdewolff** [comment]
See https://github.com/tdewolff/minify/issues/232 or https://github.com/tdewolff/minify/issues/235

In short, use Go modules or revert to an older version of Minify.

**Comment by tdewolff** [comment]
I've removed the relative paths in 1a284e70373b0504595a7c84ed51a4d5462dafbc, does this fix it?

**Comment by JayneJacobs** [comment]
I am still seeing this issue. Did you fix the master?  Locally, I deleted all /v2 references and I could build my code. That does not help when I need to dockerize the build of course.

**Comment by mh-cbon** [comment]
this worked for me, for the binary. 

```sh
gvm use go1.12
mkdir tmp && cd tmp
go mod init test
go get -u github.com/tdewolff/minify/v2
```

because i kept GOBIN to the same path as before i call for gvm, next time i reboot, even if i use an older go version like 1.11, i will still have the binary available to my command line, so this works, even if this is not good practice because it is a shared global dependency totally out of control.

Sorry if i pollute but this issue is too horrible to not leave a word........ i hope things get better in future.

**Comment by JayneJacobs** [comment]
@mh-cbon Good suggestion. I will try it.  I am confused about using tags in a container. Especially since I am using isophorphicgo which is calling /minify and does not specify a tag.
