### ISSUE TITLE
HTML: space after font-awesome icons (<i class="..."></i>) tags inside text is not preserved

### ISSUE THREAD

**Issue by supcik** [tdewolff/minify#240]
This issue is similar to #89, but for font-awesome (or similar) icons.

`Made with <i class="fa fa-heart"></i> and <i class="fa fa-coffee"></i>`

is converted to

`Made with <i class="fa fa-heart"></i>and <i class="fa fa-coffee"></i>`

How can I preserve the space between the _heart-icon_ and the word _and_ ?

**Comment by tdewolff** [comment]
You can use the `KeepWhitespace` option for the HTML minifier. I'll investigate if this issue can be resolved or not.

**Comment by supcik** [comment]
> You can use the `KeepWhitespace` option for the HTML minifier. I'll investigate if this issue can be resolved or not.

Thank you for your reply. I am using Hugo, is there a way to pass the 'KeepWhitespace' with Hugo ?

**Comment by Parent5446** [comment]
It looks like the minifier does not preserve spaces after inline elements. The fix in #89 marks certain elements as object elements, but would it not make sense to set omitSpace = true whenever encountering the end tag of an inline element?

**Comment by tdewolff** [comment]
The point is that from a HTML perspective, an empty `<i></i>` preceded and followed by a space is the same as one only preceded by a space (and not followed by a space). Only because the `<i>` is changed to `display: inline-block` makes this rule invalid. The `KeepWhitespace` is there specifically for this reason, but maybe we can make an exception with empty inline tags, so that `omitSpace = false`.

**Comment by methodman4** [comment]
A similar problem occurs when a block element is changed to `display:inline/inline-block`. More specifically: in `<div> Test1 <div> Test2 </div> Test3 </div>`, none of the spaces are preserved. A fix would be appreciated as this lib is part of Hugo. Thanks for all your hard work!

P.S. Two workarounds for anyone else hit by this: insert `&nbsp;` instead of the space (non-optimal, as this doesn't behave or always appear similarly) or insert ` <i></i>` (preserves original space and behavior).

**Comment by tdewolff** [comment]
If you change block elements to be inline elements or the reverse, it is impossible for the minifier to know. You need to use the `KeepWhitespace` option, but it is not (yet) possible to set that option in Hugo. Not sure what the plans are for Hugo to be able to set minifier options.

**Comment by tdewolff** [comment]
I wanted to add that `KeepWhitespace` should not be necessary in general, if you design you HTML correctly. It is **not recommended** to rely on whitespace for element positioning! Changing inline to block elements makes it easy for people to do so however, but changing `display` should not pose a problem for the minifier in general.

A fix in the minifier for this could be to keep whitespace after an empty inline element, but I would argue that FontAwesome is misusing spaces for element positioning and are really at fault here!

**Comment by maxatome** [comment]
Just for the record, since https://github.com/gohugoio/hugo/pull/7077 one can add the following to `config.toml` of a Hugo site:
```
[minify.tdewolff.html]
keepWhitespace=true
```
@tdewolff I do not say you are wrong about your HTML design assertion, far from it. It is just to free people relying on foreign and probably not compliant themes.

**Comment by tdewolff** [comment]
Fully agreed, that's why there's an option! ;-)

**Comment by tdewolff** [comment]
Fixed in abcbc56
