### ISSUE TITLE
SVG - invalid <rect> can break whole image

### ISSUE THREAD

**Issue by oskarwojciski** [tdewolff/minify#244]
Trying to minify svg like: 
```
<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30">
      <rect id="Rectangle_569" height="3.333"  transform="translate(101.872 76.931)" fill="#fff" />
</svg>
```

Which has invalid schema (missing width attribute for rect), skipTag() for it is being called, but because of `StartTagCloseVoidToken` instead of cutting only the _rect_ tag it is cutting all content till the end of file.

As t.hash for `StartTagCloseVoidToken` is empty we can't compare it to the rect tag, so I think one of the possibility is to count opens and closes of tags to ensure that whole broken tag is being ommited:

eg. for skipTag would be:
```
func skipTag(tb *TokenBuffer, tag svg.Hash) {
	fmt.Println("..:: Tag: ", tag)
	opens := 1
	closes := 0
	for {
		t := *tb.Shift()

		if t.TokenType == xml.ErrorToken {
			break
		}

		if t.TokenType == xml.StartTagToken {
			opens++

		}
		if t.TokenType == xml.EndTagToken || t.TokenType == xml.StartTagCloseVoidToken {
			closes++

			if t.Hash == tag || opens == closes {
				break
			}
		}
	}
}
```

Other option is to not skip such tag, but leave in current form to not break the file.
What do you think?

**Comment by tdewolff** [comment]
Thanks for the bug report, looks like a pretty severe bug!

I think what we can do is to only compare the `t.Hash == tag` when `t.TokenType == xml.EndTagToken`. In the case that `t.TokenType == xml.StartTagCloseVoidToken` we can always stop the loop in `skipTag` regardless of `t.Hash` (which is apparently not set in that case). The reason is that in the case of `xml.StartTagCloseVoidToken` there is no possibility that other tags are being contained between the start and end tag, so that `xml.StartTagCloseVoidToken` must always be of the tag being skipped. In that case the fix would be quite easy!

Do you agree?

**Comment by oskarwojciski** [comment]
Yep it makes sanse, but I am worring about case where we have SVG like:

```
<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30">
      <g id="someGroup">
          <rect id="Rectangle_569" height="3.333" width="1.11" transform="translate(101.872 76.931)" fill="#fff" />
      </g>
</svg>
```

If we want to use skipTag function on  `g` tag.
Then the results will break after first `xml.StartTagCloseVoidToken` - from rect:
```
<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30"></g></svg>
```

instead of expected:
```
<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30"></svg>
```

So still think that counting opening and closing tags in this case will work better

**Comment by tdewolff** [comment]
I've taken your code as a template but I figured we don't really need the `t.Hash == tag` anymore. If `level` is zero (or `opens == closes`) and we encounter a close tag, we can stop the skipping. This assumes a valid hierarchy of tags in SVG, but if it were invalid it would still stop skipping instead of skipping till the EOF. Let me know if you agree.

**Comment by oskarwojciski** [comment]
Yep it makes sense and seems to be working properly :D

**Comment by oskarwojciski** [comment]
Are you going to make a release with the last changes?
