### ISSUE TITLE
Howto use Middleware / Handler?

### ISSUE THREAD

**Issue by Dexus** [tdewolff/minify#246]
Hello, everybody,

i try to use this library together with github.com/kataras/iris, but i am not able to implement the library properly.

Can anyone help me? Because I only get a blank page back or nothing is changed.

Thank you very much for your help.

**Comment by tdewolff** [comment]
I'm not really able to help you out without some more information on what is not working. You can either use the middleware directly or implement your own middleware quite simply using the provided functions. Perhaps you can do some debugging regarding input/output or error codes. Let me know if you get it to work and otherwise please post a piece of code that demonstrates that the minifier is not working.
