### ISSUE TITLE
Having out of bounds slice for css for v1

### ISSUE THREAD

**Issue by hiqbn** [tdewolff/minify#250]
Can you update v1? I'm having out of bounds slice for css for v1 and crashed.

Using v1 coz I cant install v2 with the "plugin mode". Possible not to have "plugin mode" for v2 and just make v1 good?

**Comment by tdewolff** [comment]
Please do not use version 1, it is not supported anymore as clearly stated in the readme. I'm not sure what you mean with plugin mode, there are no plugins needed for `minify`.

**Comment by hiqbn** [comment]
i cant seem to 
"go get" the version two without errors even if i upgraded golang
can you provide a version of v2 without the "golang plugin" error feature?

**Comment by tdewolff** [comment]
What is the golang plugin error feature?

Is this related to https://github.com/tdewolff/minify/issues/239? Please use an older version of Go or switch to using Go modules as this is the new way to load dependencies in Go.

**Comment by hiqbn** [comment]
yes is it exactly #239 
I've used many go lang modules with 
go get [etc]

all of them work as it is. I have no idea why your module is the one causing the problem (which should never be so)

pls fix it instead of asking us to switch to older version of Go (it doesnt make sense as I have other plugins that would like to use the newer version of Go) and I have no idea how to use Go modules

when i did the go init... and go build myprogram.go, it hangs there forever.

Please fix it. Thanks in advance. It'll be of great help to everyone if this can be used as it is (the normal way)

**Comment by tdewolff** [comment]
I'm sorry, I meant switching to an older version of `minify` not of Go. Please confirm that you use `go get github.com/tdewolff/minify/v2` to get the library (don't forget the `v2` at the end). I've just tested this and it seems to work.

Or otherwise, are you using the import path `import "github.com/tdewolff/minify/v2"? Please ensure that you do. If it still hangs, please use `go build -v myprogram.go` and report the output.
