### ISSUE TITLE
How to keep images 

### ISSUE THREAD

**Issue by apoorvmote** [tdewolff/minify#286]
All of my images are removed after minify along with `robots.txt`. 

Its not easy to manually transfer images because I have folder of images for each blog post. All folders themself are missing after minify.

Is there option to keep them?

**Comment by tdewolff** [comment]
Do you mean using the cmd line tool? What command are you running? Can you explain what you did?

**Comment by apoorvmote** [comment]
Hugo is using this repo as default but it doesn't have additional option. So I did the following command
```
minify -r -o output/ .\public\ --html-keep-quotes --html-keep-document-tags
```
From output all png images were gone. I was using them for favicon and images folder from every blog post directory was missing along with `robots.txt`

**Comment by tdewolff** [comment]
Just to clarify a few things: Hugo use the minify library directly, which the command line tool does so as well. Hugo does not use the command line tool. The problem you encounter is due to the way the command line tool was implemented, namely it only processes files it can minify (HTML, CSS, ...). If you want to minify all the relevant files and on top of that copy any other file that was present, you can use the `--sync` option. This is a relatively new option, so I apreciate feedback whether it works correctly.

**Comment by apoorvmote** [comment]
`--sync` works perfectly. 

I had older version of minify that didn't have `--sync` option. After I updated minify, it works perfectly.

Also if I try to check my version with `minify --version` I get following output
```
minify version master
```
So if you could add actual version number then it would be great.
