### ISSUE TITLE
Trouble with <a href=bla/>hi</a> and <div data-value=aa/>

### ISSUE THREAD

**Issue by methodman3** [tdewolff/minify#288]
Some browsers have trouble interpreting `<a href=bla/>hi</a>` and `<div data-value=aa/>` correctly. A browser may see the / as a closing tag in the first case; and other browsers may see aa/ as the data-value in the second case.

I tracked down a solution implemented by w3-total-cache at https://plugins.trac.wordpress.org/browser/w3-total-cache/trunk/lib/Minify/Minify/HTML.php (see lines 345 to 373).

Please fix, thanks!

**Comment by tdewolff** [comment]
You should make sure that you only minify HTML5 (and not XHTML!) by this minifier. If you have XHTML, you should use the XML parser. If your HTML starts with `<!doctype html>` that should be sufficient to specify that it is HTML5, if a browser breaks on the issue of `/>` then that means that browser is broken (and will probably not render webpages correctly!). This will not be fixed because the minifier accepts only HTML5 input. Let me know if you have more questions ;-)
