### ISSUE TITLE
JS regression

### ISSUE THREAD

**Issue by bep** [tdewolff/minify#330]
```js
var x;
x = 5;
document.getElementById("demo").innerHTML = x * 10;
```

Becomes

```js
var x;x=5,document.getElementById("demo").innerHTML=x*10
```

Which does not look correct.

https://github.com/gohugoio/hugo/pull/7701

**Comment by tdewolff** [comment]
Thanks for the report, can you indicate which part is incorrect? As far as I can see `var x; x = 5` could be better reduced to `var x=5`. But otherwise `x=5; document.getElementById("demo").innerHTML=x*10` is the same as `x=5,document.getElementById("demo").innerHTML=x*10`, given that execution order with comma-expressions is from left-to-right.

**Comment by bep** [comment]
>Thanks for the report, can you indicate which part is incorrect? 

No, I cannot. I ran it through some online JavaScript "checkers" and all of them red flagged it. In Hugo we have some very simple sanity checks to check upstream libraries, and this turned red.

It wasn't obvious to me that this is correct behaviour, and it still isn't, so I will leave this (or that PR) open until i can get some ... vote of confidence from others.

**Comment by tdewolff** [comment]
Looks fine to me using ESLint (https://eslint.org/demo). What checker are you using? Are you sure it is using a recent version of ECMAScript? I'd be surprised though, this should be possible from the early versions of JS. What red flag is thrown?

**Comment by bep** [comment]
>What checker are you using?

Some of the checkers that pop up when Googling "javascript syntax checker". Note that this is probably fine, but the "probably" part make me think twice.

**Comment by tdewolff** [comment]
I've Googled "javascript syntax checker", and this came up:
- Esprima: Code is syntactically valid.
- JSHint: two warnings: missing semicolon (duh), and `Expected an assignment or function call and instead saw an expression.`. The latter happens when an expression has no effect, it gets confused here because of the comma-expression which is not "used", but really it consists of two assignment expressions which is totally fine
- beautifytools: same as JSHint
- codebeautify: 7 warnings of missing spaces and semicolons (duh), unexpected comma (not sure why)
- JSLint: 2 warnings about the same thing (`Expected ';' and instead saw ','.`), well yes, that's true but it's not wrong
- piliapp: no errors nor warnings
- validatejavascript: `error Expected an assignment or function call and instead saw an expression. (no-unused-expressions)` like before (referring to https://eslint.org/docs/rules/no-unused-expressions), and `error Unexpected use of comma operator. (no-sequences)` (referring to https://eslint.org/docs/rules/no-sequences)

These are all style warnings to promote good code style. There is no invalid syntax nor error nor bad behaviour. If you observed unexpected behaviour though, please let me know.

Next time it would be helpful if you provided what part is wrong about the example, the name of the tool that fails and what error it throws. That would really help solving issues quickly.

**Comment by bep** [comment]
OK, people on the Hugo trakcer seem to (mostly) agree with you. Sorry for the noise.
