### ISSUE TITLE
Invalid JS Minify

### ISSUE THREAD

**Issue by stackch** [tdewolff/minify#340]
I have the following small JS Code:

(function ($) {
})();

The minifier result is:

!function(a){}()

What about the ! mark?

**Comment by LiuJun0** [comment]
## Use this parameter: --js-keep-var-names, it can meet your requirements

## Demo

```
m.Add("text/javascript", &js.Minifier{
	KeepVarNames: false,
})
```

#### Use Command line tool mode：
```
minify --js-keep-var-names -v -r -o output entry
```
#### After compress code
```
!function($){}()
```

**Comment by tdewolff** [comment]
In JS there are syntactically two kinds of function: function declarations such as `function a(){}` which is the usual way people define functions, and function expressions such as `(function(){})` or e.g. `a = 5 + function f(){}()`. In the latter case, the function name is optional and the function is usually defined and executed. In order to make sure a statement starting with `function(` is parsed as an expressions, we can add `!` in front. This however interferes with the returned value of the function, thus we should enclose in `(` and `)` instead! Thanks for the bug report!
