### ISSUE TITLE
<li> end tag removed, resulting in changed semantics

### ISSUE THREAD

**Issue by CoolOppo** [tdewolff/minify#360]
Hi, I have some HTML that looks like this:

```html
<ul class="footer__list">
    <li class="footer__item">
        <span>number</span>
        <small>(123) 456-7890</small>
    </li>
    <div class="sep"></div>
    <li class="footer__item">
        <span>email</span>
        <small>blah@gmail.com</small>
    </li>
    <div class="sep"></div>
    <li class="footer__item">
        <span>address</span>
        <small>123 address.com lane</small>
    </li>
</ul>
```

And when put through minify, it turns into this:

```html
<ul class=footer__list>
    <li class=footer__item><span>number</span>
        <small>(123) 456-7890</small>
        <div class=sep></div>
    <li class=footer__item><span>email</span>
        <small>blah@gmail.com</small>
        <div class=sep></div>
    <li class=footer__item><span>address</span>
        <small>123 address.com lane</small>
</ul>
```

Chrome and Firefox both parse this as if the `<div>` is inside of the `<li>`, which is not how the original markup worked.

I'm aware that there is a flag to stop the end tags from being removed, but I figured this was just plain unintended behavior for `minify` to actually change the semantics of the markup like this.

Thanks.

**Comment by tdewolff** [comment]
Thanks for reaching out! Actually, in HTML5 it is not allowed to have elements beside `<li>` inside `<ul>` tags. So that in your case the `<div>` is actually an error that seems to be ignored by browsers. See the spec at https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element.

Testing with the HTML5 validator at https://validator.w3.org/nu/#textarea, it will throw:
```
Error: Element div not allowed as child of element ul in this context. (Suppressing further errors from this subtree.)
```

Hopefully that clears it up. The minifier expects valid HTML5 to function properly. In your case you should probably convert the `div` to `li`, or put the divs inside the lis.

**Comment by CoolOppo** [comment]
Alright, makes sense to me.
