### ISSUE TITLE
Feature request: KeepWhitespace for Javascript

### ISSUE THREAD

**Issue by jamierocks** [tdewolff/minify#368]
Similar to the HTML and XML minifiers, it would be great if the JS minifier could support KeepWhitespace.

**Comment by tdewolff** [comment]
Hey Jamie, thanks for the suggestion. For HTML and XML there is a specific function that whitespace has, so that when the users use some bad practices of HTML or XML they need to use the switch to make sure that the minified output displays the same result as the original.

For JS not so much, there is no significance of whitespace other than to separate keywords. So I'm not sure what the function `KeepWhitespace` should have for JS, other than perhaps to make it more readable for humans? What is the use case?

**Comment by jamierocks** [comment]
Hey, thanks for the quick reply! Interesting to know the context on HTML and XML.

Being more readable for humans is part of it - but the larger context is that I use minify in a static site generator, and use GitHub Pages for deployment.

The site is generated from live data, and althought it infrequently changes - Git handles this much better when 1 short line changes vs 1 large line (I could forgo history, but it is useful to see changes in the data).

Naturally I can understand if this isn't something you'd want to support.

**Comment by tdewolff** [comment]
I don't think human readability is something the library should focus on, but breaking up large change diffs for git commits is a very practical problem we could mitigate.

In JS we could achieve this by replacing whitespace in certain statements (such as `let a=5`) by newlines. Additionally, we could replace semicolons `;` by newlines in certain situations. Here we replace one byte by another, and thus the file size will stay the same even though we have now added newlines. The problem is that many people think that JS is not really minified if there are newlines present, so we should indeed introduce an option I guess.

The newlines will be pretty arbitrary, but I guess if the goal is to make git diffs shorter that could be possible.
