### ISSUE TITLE
Feature request: JS benchmark

### ISSUE THREAD

**Issue by co-in** [tdewolff/minify#377]
I compared Uglify3 Compression Ratio

`uglifyjs --compress --mangle --mangle-props --toplevel --output ./result.uglify.js -- ./jquery-3.5.1.js ./jquery-1.12.4.js ./jquery-ui-1.12.1.js`
374626 bytes

`minify --bundle --output ./result.miinify.js  ./jquery-3.5.1.js ./jquery-1.12.4.js ./jquery-ui-1.12.1.js`
440947 bytes

Maybe you can borrow some algorithm from Uglify3? 15% this is a significant decrease

**Comment by tdewolff** [comment]
True, but this is because UglifyJS is a very advanced minifier, together with the Google Closure compiler. That is, they use different passes over the files in order to reduces the most. This is not possible as this minifier is only single pass, which is the same reason why `minify` is about a 100x faster. From my own measurements I'm surprised that the different is so big (see https://github.com/tdewolff/minify#compression-ratio-lower-is-better). Please uncheck the `toplevel` as that would be unfair to compare. Minify could (but doesn't) minify the toplevel as those variables could be used in other files. Additionally, `mangle-props` is really quite an unsafe feature. Please uncheck those two and if there still is a large difference I should take a look what's happening. Thanks for the heads-up!
