### ISSUE TITLE
Preserving random newlines inside paragraphs?

### ISSUE THREAD

**Issue by tronorama** [tdewolff/minify#430]
Please see the screenshot below. Is this the way the minifier is supposed to work, or is it a bug? The browser rendering engine is doing what I expect with the various newlines in this test `<p>` without any `<br>` elements. But the minifier is only discarding some, not all, of the newlines. Since it is not inside a `<pre>` or `<code>` block, I was expecting all of the newlines to be discarded (like the browser rendering engine is doing here).

My minify config for this environment is at bottom left. I've also highlighted everything inside the `<p>` source so you can also see where the actual space characters are.

![hugo-minify-test](https://user-images.githubusercontent.com/7062385/129434189-7100b60e-2d74-42ee-ab61-5394e25224d0.png)

**Comment by tdewolff** [comment]
I don't think this is a problem. You could replace the newlines with spaces and get the same output size and the same HTML page. Note that your HTML layout needs a space right before the `|` bar to be correctly layed-out. Instead of a space the library uses a newlines (because the original whitespace sequence contained a newline), which doesn't really mean anything significant. This should still be the smallest HTML to which it can compress.

**Comment by tronorama** [comment]
I guess if you feel that a minifier not at least doing (even optionally, as specified in a config file) the same thing the browser does with the newlines, then there's no point in me continuing here.

I would only possibly suggest to maybe note in the README or somewhere that it won't do what one might think it would do compared to what a browser rendering engine would do, so one needs to manually remove any unwanted newlines from their source.

**Comment by tdewolff** [comment]
Well, the minifier does exactly the same thing as what the browser does w.r.t. whitespace and newlines, namely they both follow the HTML5 specification. If you want the source code to follow a certain style that would be a completely different goal than what the minifier tries to do. The minifier is only concerned with getting the smallest file size that is equivalent to the original source. It actually keeps newlines in whitespace sequences only because this helps to mitigate extremely long lines which causes problems on some devices / servers.

If instead you'd like to "style" your source, much like a beautifier, you could get a similar result though if you'd just replace `\n` with a space after minifying.
