### ISSUE TITLE
removal of unrequired end tags leaves empty newline

### ISSUE THREAD

**Issue by esdnm** [tdewolff/minify#442]
using `minify --html-keep-whitespace` on

```html
<h1>h1</h1>
<ul>
<li>this is a list.
more things.
</li>
<li>one more
item.
</li>
</ul>
```

produces,

```html
<h1>h1</h1>
<ul>
<li>this is a list.
more things.

<li>one more
item.

</ul>
```

should those empty newlines be there?

**Comment by tdewolff** [comment]
Should be fixed now, please let me know if you have any further problems!

**Comment by esdnm** [comment]
> Should be fixed now, please let me know if you have any further problems!

Thanks!

I currently don't have any further problems. But! I am little surprised by the commit. You flipped the branches and It works. I would like to know what has happened.

**Comment by tdewolff** [comment]
Hehe I had to take a second look as well. The fact is that `o.KeepWhitespace = true` and would initially _always_ result in setting `omitSpace = false`. By reordering however, we first check whether this is a block closing tag, if so set `omitSpace = true` and otherwise to `false`. This creates more instances where `omitSpace` is `true` that was previously the case, namely after closing tags for blocks.
