### ISSUE TITLE
JS minify produces broken code

### ISSUE THREAD

**Issue by jmooring** [tdewolff/minify#445]
Input

```js
var a = 1;
function f() {
  return 1;
}
var { min, max } = Math;
function g() {
  return 2;
}
```

Output

```js
var a=1,min,max;function f(){return 1}{min,max}=Math;function g(){return 2}
```

Reference (<https://jscompress.com>)

```js
var a=1;function f(){return 1}var{min:min,max:max}=Math;function g(){return 2}
```

This is not a new issue. I tested 2.9.10 - 2.9.22. Only 2.9.21 was different (very different).

**Comment by tdewolff** [comment]
This bug has been confirmed, working on a fix!

**Comment by tdewolff** [comment]
Still working on the fix, it is quite complex as it requires some restructuring of the code. I use the opportunity to push through related improvements for minification.

**Comment by tdewolff** [comment]
The shortest output should be `a=1;function f(){return 1}var{min,max}=Math,a;function g(){return 2}`

**Comment by tdewolff** [comment]
I've pushed out a fix for your issue, and besides fixing a bug most benchmark targets get smaller still (improved minification). Unfortunately this comes at a 2% cost in time. The `ace.js` sample actually gets bigger with this update, which is likely because complex (array or object) variable declarations don't get merged yet. Hopefully that gets fixed as soon as it is supported.

In the meanwhile, if you can please test the patch to see if your JS still runs as expected.
