### ISSUE TITLE
Too many recursions on links

### ISSUE THREAD

**Issue by EthraZa** [tdewolff/minify#465]
At my system I got some soft links like 
```yml
dev -> .//
```
created with `ln -s ./ dev` command.

But I had to delete all of them if I want to use **minify** since it cannot handle the situation, given an error saying about too many recursions.

There is some switch option I can use to avoid it by ignoring the specific paths or the kind of file? In add, I would like to ignore .git paths too.
Actually I'm using the following switchs:
```php
minify --match '\.(css|html|js|json)$' -sarp "$dev/" -o "$prod/"
```

Maybe detect links that point to itself causing recursion would be a grest add to minify.

Thanks.

**Comment by tdewolff** [comment]
Thanks for the suggestion. I've been looking into symlink recursion but it's not a trivial problem. You can have symlinks pointing to themselves, 2 or more symlinks pointing to each other cyclically, or in case of having `-r` directory recursion enabled, the symlink could point to one of the ancestor directories. In fact, the same error happens when you call `cp -rL dev prod`, telling me that your particular case is very uncommon and is not handled properly by standard system tools.

Additionally, I don't think an `--exclude` option is on the horizon. As this tool tries to mimic the `cp` command, it seems this can easily be solved using an old Linux proverb: "do one thing and do it well". I don't think the minify tool should include all sorts of filesystem features if you could use the `ls` or `find` tools in combination with other tools for filtering. I agree that it might be handy, but not sure if we should expand the scope of features for minify much more.

**Comment by EthraZa** [comment]
I see, I prefer a KISS aprouch as well.

Anyway, whyle I was reading your response, before get in the second paragraph, I was thinking like:
> When minify goes inside a directory, it could add this path to an in-memory exclude list, so it does not do this directory anymore, even with symlinks pointing at it.
But then I got in the second paragraph. :)

So, I didn't tested this commands, but there are some possible solutions to myself:
```php
shopt -s extglob; minify --match '\.(css|html|js|json)$' -sarp !(b*) -o prod/
```
or
```php
find dev/ ! -name "exclude*" -exec minify --match '\.(css|html|js|json)$' -sarp !(b*) -o prod {} \+
```

**Comment by tdewolff** [comment]
Exactly! Actually, I was thinking about a solution along similar lines until I discovered that `os.Stat` is the problem as it follows symlinks automatically (which is what we want in general). The other function is `os.Lstat` which does not follow symlinks, but we'd have to manually follow them to emulate `os.Stat` and indeed keep an in-memory list of directories already visited to avoid recursion.

**Comment by EthraZa** [comment]
I don't know how minify scan files to cp/minify, but, if it's something like a glob function, that you do first and then act over the list, you could do 2 searchs, one "without symlinks" and other "symlinks only" excluding the paths from first search and them, marging results and keep using os.Stat.
Just trying to help the brainstorning here.

**Comment by tdewolff** [comment]
Thanks for the comment. As this will not be included in the tool I will close this issue for now...
