### ISSUE TITLE
A small question about HTML compression

### ISSUE THREAD

**Issue by jie702428** [tdewolff/minify#592]
I'm using `minify` to compress HTML code, but found a small problem!

Test HTML:
```
<script src="111.js"></script>
<script src="222.js"></script>
<span>111</span>
<span>222</span>
```

The result I want to get is:
`<script src="111.js"></script><script src="222.js"></script><span>111</span><span>222</span>`

But `minify` doesn't do what I want, the output is still:
```
<script src="111.js"></script>
<script src="222.js"></script>
<span>111</span>
<span>222</span>
```

Is there any way to solve this problem?

Thanks!🙂

**Comment by tdewolff** [comment]
Not really, because there's a detail that is easy to miss: there is a whitespace (a newline) between the two spans which makes the browser show `111 222` (notice the space) and not `111222`. The result you expect would show the latter, which is not the same!

I did expect that the newline after both `</script>` tags could be removed though, let me investigate and get back to you!

**Comment by jie702428** [comment]
Ok, very much looking forward to your reply!

**Comment by tdewolff** [comment]
Should be fixed now!
