### ISSUE TITLE
[CMD] Errors happened, but file minificated

### ISSUE THREAD

**Issue by awsom82** [tdewolff/minify#63]
If we try to minificate [that file: style.css](https://github.com/tdewolff/minify/files/33955/style.css.txt), 
`minify` will shout with error, but file will be minificated

```ERROR: cannot minify input style.css: unexpected token in declaration, expected colon token```

**Comment by tdewolff** [comment]
I suspect this is because the error is found half-way through the file. The first part of the file has been written away already, because it is streamed.

If an error occurs, should it delete the (incomplete) output file? What about when overwriting files? The input file should be renamed to `.tmp` and renamed back when errors have occurred I think.

**Comment by awsom82** [comment]
Yeah, my bad. Sorry for incorrect report of issue.
I think if error occurs, it must keep original file.

**Comment by tdewolff** [comment]
Fixed in 0441c272eb4af82e11bf35db5a1482f7c183678f

When overwriting the input, a backup is made first. When success the backup is removed, when fail the backup is renamed to the original name.
