### ISSUE TITLE
Magnifying CSS in a HTML document which uses Mustache template, incorrectly minifies

### ISSUE THREAD

**Issue by softwarespot** [tdewolff/minify#710]
I have the following classname, which is being minified in a html document. 
I then read that html document and run it through [mustache.js](https://github.com/janl/mustache.js), whereby it substitutes `{{id}}` for a unique identifier. The issue is that `minify` is removing the space between the last `}` and `.`, thus affecting the styles on the page.

Do you have an advice? As I am aware `}` is valid in a CSS classname.
Thanks for the wonderful product!

```
<style>
.fr-{{id}} .medium-size-control-buttons-visible:hover {
     opacity: 0.5;
}
</style>
```
**Repoducer:** https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRmNzcyZjc3MtcHJlY2lzaW9uPTAmc3JjPS5mci0lN0IlN0JpZCU3RCU3RCsubWVkaXVtLXNpemUtY29udHJvbC1idXR0b25zLXZpc2libGUlM0Fob3ZlcislN0IlMEQlMEErKysrK29wYWNpdHklM0ErMC41JTNCJTBEJTBBJTdE

**Comment by tdewolff** [comment]
Yes, this is a bit tricky because the brackets are not valid CSS syntax as far as I know. The CSS spec is a bit chaotic, but it looks like that the CSS3 syntax allows any component value in a qualified rule, but then https://www.w3.org/TR/selectors-4/#grammar tells us that (correct me if I'm wrong) curly brackets are not allowed.

To be pedantic, you're not minifying HTML but a template file that would become HTML after processing by Mustache. What happens is that since it is not valid CSS, the CSS minifier will not produce valid output, and the HTML minifier would skip the `<style>` tag. Unfortunately there isn't much I can do here, unless we plan on supporting template tags in CSS (which is not trivial!). You're only option is pass it by Mustache first before minifying...

**Comment by softwarespot** [comment]
Yes I should've checked the grammar myself, but I asked ChatGPT and it said it was valid CSS, so who was I to question the answer!
I have had time to think about it and it makes sense why `{` & `}` wouldn't be valid in a CSS selector, like duh! :smile: 

Quite clear when I know what `ident-token` is too.
```
<class-selector> = '.' [<ident-token>](https://www.w3.org/TR/css-syntax-3/#typedef-ident-token)
```
Oh and you are correct about minifying a Mustache template, I would say your are **NOT** being pedantic this time :smile:  

FYI, I am asking on behalf of someone else, so I think I will suggest the solution of specifying custom tags that are spec compliant and then as the minifier is concerned, it's valid HTML/CSS.

Thanks for answering so quickly and providing this functionality in Go, a language I use every day!

**Comment by tdewolff** [comment]
Awesome, thanks for getting back! Let me know whenever you have a problem with this library ;-)

**Comment by softwarespot** [comment]
Actually using `.fr-{{id}}-append .other-classname` preserves the whitespace, but I am reluctant for the other developer to use, as I cannot guarantee in this future that minify won't break this. Just thought you should know
