### ISSUE TITLE
Javascript option to preserve string newline or char codes

### ISSUE THREAD

**Issue by naturedamends** [tdewolff/minify#717]
I would like to preserve newline chars when in strings, such that I can write programs that operate on them. Currently it changes the output of the program.  `\r\n` is being replaced with a single `\n`.  As a tagged literal with a new line char.  I need the \r

for example:

```
const something = '\r\n';
```

is replaced with
```
const a = `
`;
```

which is completely different. Its char code is not 13, 10. Its simply 10

**Comment by tdewolff** [comment]
This was fixed in the latest release, a sequence of `\r\n` (or 0x5C 0x72 0x5C 0x6E) was previously converted to 0x0D 0x0A (but not just 0x0A as you mention...), but it now becomes 0x5C 0x72 0x0A. That is, `\r` is now kept as-is (also when alone). Please let me know if the latest release works for you.

**Comment by naturedamends** [comment]
> This was fixed in the latest release, a sequence of `\r\n` (or 0x5C 0x72 0x5C 0x6E) was previously converted to 0x0D 0x0A (but not just 0x0A as you mention...), but it now becomes 0x5C 0x72 0x0A. That is, `\r` is now kept as-is (also when alone). Please let me know if the latest release works for you.

I have just disabled it for the moment. Why are you thinking that `\r\n` is not `0x0A 0x0D, at least in ascii hex.

**Comment by naturedamends** [comment]
So when it transforms it within a javascript string.

it needs to retain the \r characters?

**Comment by tdewolff** [comment]
Not sure if I understand the problem, please try the last version and tell me if you still have a problem.

There is a difference between escape sequence (the characters '\' 'r' and '\' 'n') and literal (0x0D and 0x0A respectively) line terminators, but in some cases we may convert escape sequences into literals:
- Inside single and double quoted strings: literal line terminators are not allowed, except when preceded by a backslash in which case it is an empty string (used to continue writing a string to the next line without inserting a newline in the string)
- Inside backtick quoted string (template literals): literal line terminators, including 0x2028 and 0x2028, are allowed but noting that 0x0D and the sequence 0x0D0A are both interpreted as 0x0A. This means we may convert the escape sequence `\n` to its literal, but `\r` not (this was fixed in the commit).

**Comment by naturedamends** [comment]
Using the latest version of your package. Node bindings.

```
{
  "type": "module",
  "dependencies": {
    "@tdewolff/minify": "^2.20.34"
  }
}
```
```
(() => {
  // <stdin>
  function obj(h) {
    obj.EOL = "\r\n";
  }
  var a = new obj();
  console.log(obj.EOL.split().map((a2) => a2.charCodeAt(0)));
})();
```
```
(()=>{function e(){e.EOL=`\r
`}var t=new e;console.log(e.EOL.split().map(e=>e.charCodeAt(0)))})()
```
```
node one.min.js 
[ 13 ]
```

I think it should be [13,10]? Not sure why its skipping the 10 here, As you say it should template literal should transform a newline character.



I have just tried with the latest hugo (0.127-extended)  i can easily get. And i get the same result.  There will be no issue if you replace with ` 0x5C 0x72 0x5C 0x6E` like you said.

I'm using `hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended linux/amd64 BuildDate=2023-12-08T08:47:45Z VendorInfo=gohugoio` during the builds above.

Iin the hex dumps. It transforms to incorrect code. Since it replaces the literal chars with whitespace characters. 


```
function obj(h) {

    obj.EOL = '\r\n'
}
const a = new obj();
console.log(obj.EOL.split().map(a => a.charCodeAt(0)))
```
```
(()=>{function e(){e.EOL=`
`}var t=new e;console.log(e.EOL.split().map(e=>e.charCodeAt(0)))})()
```

```
[10]
```

And javascript not parsing the `0xD`. When not transforming the syntax, it retains the correct chars.

**Comment by tdewolff** [comment]
That looks correct. You can disable template literals by setting the `Version` to below 2015 (template literals are defined in ECMAScript 2015).

> Iin the hex dumps. It transforms to incorrect code. Since it replaces the literal chars with whitespace characters.

What do you mean, it works in your example above but not with Hugo? Perhaps they haven't updated the dependency?

**Comment by naturedamends** [comment]
> That looks correct. You can disable template literals by setting the `Version` to below 2015 (template literals are defined in ECMAScript 2015).
> 
> > Iin the hex dumps. It transforms to incorrect code. Since it replaces the literal chars with whitespace characters.
> 
> What do you mean, it works in your example above but not with Hugo? Perhaps they haven't updated the dependency?

Yeah. So many versions and test cases linked to versions, it’s hard to say words. Lol. Sorry.

- Using hugo < 0.127 the output of my program changes.
- My program works using your standalone program, from npm. version above
- They may have updated. But it hasn’t  reached downstream where I am downloading from.

**Comment by naturedamends** [comment]
> That looks correct. You can disable template literals by setting the `Version` to below 2015 (template literals are defined in ECMAScript 2015).
> 
> > Iin the hex dumps. It transforms to incorrect code. Since it replaces the literal chars with whitespace characters.
> 
> What do you mean, it works in your example above but not with Hugo? Perhaps they haven't updated the dependency?

Just updated hugo and it seem to work.

```
(() => {
    function e() {
        e.EOL = `\r
`
    }
    console.log(e.EOL),
    console.log(e())
})()
```
