### ISSUE TITLE
xmlns attribute is required for single SVG file

### ISSUE THREAD

**Issue by marmooo** [tdewolff/minify#720]
#704 has a bug.

It is true that inline SVG does not require an xmlns attribute,
but it is required if we are loading the SVG file from HTML
or treating it as a single file.

If you open an SVG without an xmlns attribute in a browser,
you will see that the image will not be displayed.

**Comment by tdewolff** [comment]
Thanks for raising this issue. The XMLNS attribute should only be removed when the SVG document is "inline". This is only activated for SVG elements inside HTML. Otherwise, a regular SVG document is not considered inline and should thus not remove the XMLNS attribute. It is strange that this _does_ happen for you, could you show me an example that reproduce this behaviour?

**Comment by marmooo** [comment]
Sorry for the lack of examples.
After further investigation, it appears to be a random bug.
It seems to happen about 70% of the time.
Since it was not possible to check without a certain number of files,
I will provide an example of a repository where the error occurs.

```
go install github.com/tdewolff/minify/v2/cmd/minify@latest
https://github.com/marmooo/touch-kanji
cd touch-kanji
minify src/favicon/favicon.svg  # --> ok
minify -r docs -o .  # --> sometimes fail
```

The easiest way to check is to enter the following commands:
```
cd touch-kanji
minify -r docs -o .
git status  # <-- if If docs/favicon/favicon.svg is added, it's a bug. 
```

**Comment by tdewolff** [comment]
Good point, this should be fixed in the latest release!
