### ISSUE TITLE
Accessing property of object should be considered as side effect-able expression.

### ISSUE THREAD

**Issue by hyp3rflow** [tdewolff/minify#725]
If statement and its body should not be removed by minifier because it has obvious side effect.

```javascript
const b = {
  get c() {
    console.log("hi");
  }
};

if (true){
  const d = b.c; // this makes side-effect ("hi")
}
```

this minifies into:
```javascript
const b = {
  get c() {
    console.log("hi");
  }
};
```

**Comment by tdewolff** [comment]
Nice one, would simply `const d = e` never be a side-effect, or could `e` be some type that acts on its access?

**Comment by tdewolff** [comment]
I believe that simply and only using a variable in an expression is already considered a side-effect. I would be happy to hear otherwise because I don't know how that could cause a side-effect. Is there a function in a class that is called each time a variable is used?

Anyways, the bug you stated was fixed, thank you!

**Comment by hyp3rflow** [comment]
well, I'm not confident on enumerating cases that accessing simple variable can make side-effect, but with `with` statement it could be possible like below.

```javascript
with ({ get a() { console.log("hi") } }) {
  a; // console.log occurs!
}
```
