### ISSUE TITLE
Minify directory of files and output single minified version

### ISSUE THREAD

**Issue by hydrajump** [tdewolff/minify#75]
Hi I'm using the `minify` cmd tool and I tried to minify a directory containing multiple css files, but instead of getting a single output file I got a minified version of each input.

Is there a way to minify and concatenate multiple files using the cmd tool? If not, what is your recommendation a) concatenate all files first and then run minify or b) minify each file and then concatenate the minified files?

Thanks.

**Comment by tdewolff** [comment]
Hey, yes the minify tool will minify the files separately. This is intended behaviour.

I think concatenating the files first would be preferred. It might give slightly smaller output files because the point where the files are joined will be minified too, but in general shouldn't really affect the result.
