### ISSUE TITLE
HTML: make options compatible with HTMLMinifier

### ISSUE THREAD

**Issue by luixxiul** [tdewolff/minify#76]
It would be great if options of HTML minification becomes compatible with [HTMLMinifier](https://github.com/kangax/html-minifier#options-quick-reference), which is used by grunt-contrib-htmlmin and therefore easy to understand for most developers.

**Comment by luixxiul** [comment]
``KeepWhitespace`` maybe corresponds to ``collapseWhitespace`` and ``preserveLineBreaks``.

**Comment by tdewolff** [comment]
Well, this minifier works different in the way it treats whitespace. As the sensible default is to strip all whitespace, the option is reversed (ie. `KeepWhitespace` and not `CollapseWhitespace`). Also because the default whitespace removal algorithm is better than the mentioned HTMLMinifier, because `minify` recognizes phrasing elements and does more aggressive whitespace removal for those elements, the need for those options is somewhat shifted.

Instead the options are designed for specific needs, ie. `KeepWhitespace` is for when you want to do file versioning. Now I'm starting to doubt whether this option makes sense, as you should be versioning your original file not the minified one...nor should you edit minified files. Anyways, it's in now.

I think the options convey very clearly what they do, do you have a specific case where there was confusion?

**Comment by luixxiul** [comment]
> I think the options convey very clearly what they do, do you have a specific case where there was confusion?

I think there is not. Implementing them as they are might works well for the most cases, IMO.

**Comment by tdewolff** [comment]
Would you prefer to have separate `CollapseWhitespace` and `PreserveLineBreaks` options?

With respect to options I believe in less-is-more, so I'm hesitant to add new options. However, if you can provide a valid practical use for such options I will take it into consideration. Also, changing the names would break the code of current users.

`KeepWhitespace` doesn't keep all whitespace that's true. It collapses all whitespace to one space (or newline). That is the least amount of characters to be HTML semantically equivalent to the original.

**Comment by luixxiul** [comment]
I cannot provide an example of such case, nor do I know the background both of them were introduced. Though I believe some, including me, prefer the separation, I would prefer the speed over it.
