### ISSUE TITLE
cmd: Add concatenation support

### ISSUE THREAD

**Issue by tdewolff** [tdewolff/minify#94]
Add concatenation of all files as a feature for the command line tool. This would only work in a non-concurrent setup with files of the same mimetype. It would trigger when you input multiple files or a directory but one output file.

**Comment by escholtz** [comment]
Support for inlining files referenced by `@import` statements in css would be great.

**Comment by tdewolff** [comment]
That would be a nice feature of the command line tool I agree. I will think about it!

However this would not be part of the library, since it is not a minification feature.

**Comment by tdewolff** [comment]
Accepting `@import` statements is actually quite an overhaul of the current workings of the command-line tool. This would not be something I can undertake soon...

**Comment by escholtz** [comment]
No worries, `cat` is enough to get the job done.

**Comment by tdewolff** [comment]
How do you mean using `cat`?

With this commit it is possible to use `minify --concat -o style.css head.css main.css foot.css` and have all three CSS files concatenated to `style.css`

**Comment by tdewolff** [comment]
Oh well, one could simple use `cat` indeed to read-in multiple files and use concatenation that way.

Do you think concatenation should still be supported by this tool? I think I should undo this commit to reduce complexity of the tool. What do you think?

**Comment by escholtz** [comment]
My apologies if I sidetracked this issue with the `@import` request. I recently switched to minify from [cleancss](https://github.com/jakubpawlowicz/clean-css) which had support for inlining `@import` statements automatically (which is why I requested it). Once I stepped back for a second and thought about it, I realized that using cat and piping to minify was simpler. cleancss even has an example of this in their README:
`cat one.css two.css three.css | cleancss -o merged-and-minified.css`.

I think it's up to you in deciding what philosophy you want to follow. The unix philosophy is to do one thing well rather than adding lots of features that overlap with other programs. Others prefer an all-in-one solution with lots of features.

I tend to prefer simplicity and the unix philosophy.

If you do decide to revert the change, I would recommend including a `cat` example in your README since it's a common use case for those considering your tool.

**Comment by tdewolff** [comment]
> I tend to prefer simplicity and the unix philosophy.

I agree with this statement.

However, if watching file changes would support more cases, concatenation might be a valid feature that would be non-trivial using `cat`, see #104. Unless I find a way to separate file watching from the tool, since it is so complex, I will leave this in a little longer and ponder some more :)

**Comment by ef2k** [comment]
For any future readers, I made https://github.com/ef2k/stylecat to automatically inline @import css before passing it to minify. Hope it's of use!
