### ISSUE TITLE
Html minifier never returns an error

### ISSUE THREAD

**Issue by mikegleasonjr** [tdewolff/minify#95]
Even if a document is invalid and the `lexer` returns `html.ErrorToken`, `nil` is always returned from the `Minify` function.

The minified result is incomplete as it returns the minified HTML up to the point where the error is found.

**Test case (add the byte 0x00 anywhere in a valid HTML file):**

```
echo -e "\x00" > test.html
cat valid.html >> test.html
```

**The problem ([minify/html.go](https://github.com/tdewolff/minify/blob/master/html/html.go#L71))**:

```golang
	[...]
		case html.ErrorToken:
			if l.Err() == io.EOF {
				return nil
			}
			return l.Err()   // <------ always nil
	[...]
```

EDIT: using v2.0.0

**Comment by mikegleasonjr** [comment]
Same with JS, `l.Err()` is always nil and I guess CSS does that too?

**Comment by tdewolff** [comment]
Hmm, yes this is a bug. It has to do with 0x00 being interpreted by the parser that the reader has an error, so it quits parsing but Err is nil since the reader didn't have an error after all. That it quits parsing is correct though, since 0x00 is a parser error according to the HTML spec. You are correct that it should report an error then.

Will fix this soon.

**Comment by tdewolff** [comment]
You said that for JS also could have `l.Err() == nil`, but I don't see how. How did you get that result?

See https://github.com/tdewolff/parse/blob/master/js/lex.go#L155, that is the only part that returns `ErrorToken`.

**Comment by mikegleasonjr** [comment]
Well I am writing unit tests for an app and I want it to fail when there's invalid js provided.

Every text input I feed to the minifer, even random text never fails... Do you have a test case for me?

**Comment by tdewolff** [comment]
Well it is designed to fail as little as possible and leave any non-spec input as it is. The parser assumes that the input is valid spec-compliant JS. Since the JS parser is very basic, it has no way to fail (ie. no grammar tests).

The only way I can see it fail is when `Lexer` fails, which happens only when `io.Read` returns an error. You can achieve this by using a test reader that always returns an error, see https://github.com/tdewolff/test/blob/master/readers.go#L23 for example.

**Comment by mikegleasonjr** [comment]
Sounds good to me! Thanks for your explanations!
