### ISSUE TITLE
CSS minifier: animation names become lowercase

### ISSUE THREAD

**Issue by mikegleasonjr** [tdewolff/minify#99]
**Test case:**

```
.et_pb_animation_bottom.et-animated {
	animation: fadeBottom 1s 1 cubic-bezier(0.77, 0, 0.175, 1);
}
```

- on branch 2.0.0 (**BUG**, **fadeBottom** became lowercase):

```
.et_pb_animation_bottom.et-animated{animation:fadebottom 1s 1 cubic-bezier(0.77, 0, 0.175, 1)}
```

- on branch master (**BUG**, **fadeBottom** became lowercase):

```
.et_pb_animation_bottom.et-animated{animation:fadebottom 1s 1 cubic-bezier(0.77, 0, 0.175, 1)}
```

**EDIT:** Animation names (in short-hand notation or in animation-name), are case sensitive in latest versions of FF, Safari and Chrome on OSX (what I could test).

**Comment by mikegleasonjr** [comment]
Also when we have something like:

```css
.blah {
   animation-name: fadeLeft;
}
```

**Comment by tdewolff** [comment]
This is because CSS3 is case-insensitive except for a few things that are out of its control. Namely: id, element and class names are case-sensitive.

Apparently custom idents are case-sensitive too: https://www.w3.org/TR/css3-values/#custom-idents

There are more cases:
- https://www.w3.org/TR/css3-values/#attr-notation
- `url` property function
- `content` property

**Comment by mikegleasonjr** [comment]
Thank you very much Taco!
